### ISSUE TITLE
食料問題班PowerPoint

### ISSUE THREAD

**Issue by RyotaTokuda** [RyotaTokuda/team-nodaiaken#1]
1. 問い　　貧困　広く
得田

1. 世界　ストチル
星

1. フィリピンの貧困の割合の図
得田

1. 食べ残し　習慣　フードロス
えりさん

1. フードロス
えりさん

1. グリーン　ストチルの食べる量　比べる
金子さん

1. フィリピン　米
星

1. フィリピンの貧困とは

1. 食料問題まとめ

**Comment by bobtochi** [comment]
順番変えませんか？

**Comment by RyotaTokuda** [comment]
- [ ] 完了

1. あああああああ

1. ああああああああ

- あああああああ

- あああああああ

**Comment by bobtochi** [comment]
８、フィリピンの貧困とは
が新しく追加されたよ

**Comment by RyotaTokuda** [comment]
> 1. 問い　　貧困　広く
>    得田
> 2. 世界　ストチル
>    星
> 3. フィリピンの貧困の割合の図
>    得田
> 4. 食べ残し　習慣　フードロス
>    えりさん
> 5. フードロス
>    えりさん
> 6. グリーン　ストチルの食べる量　比べる
>    金子さん
> 7. フィリピン　米
>    星
> 8. フィリピンの貧困とは
> 9. 食料問題まとめ

@bobtochi 
こちらでよろしいでしょうか？

**Comment by RyotaTokuda** [comment]
## パネルについて
### font-size
- タイトルは128

- 本文 84

- 強調したい部分は太文字にしても良い
