### ISSUE TITLE
本当だ簡単だった

### ISSUE THREAD

**Issue by Designblitz** [RyotaTokuda/team-nodaiaken#19]
### 小田

- [ ] 会員からAA研への入金がわかるテンプレ作成

- [ ] テンプレをテンプレ用のシートに変換する

**Comment by Designblitz** [comment]
しくじった

**Comment by RyotaTokuda** [comment]
> しくじった

3点マークからeditできるのと、closed された issue だったから respon させておいた

**Comment by Designblitz** [comment]
なるほどね
でも新規で作ってる
名前の変更がわからなかったから

**Comment by RyotaTokuda** [comment]
> なるほどね
> でも新規で作ってる
> 名前の変更がわからなかったから

上の方にある new issue の隣のeditで編集できるよー、使わなくなったissueは下の close でいったん見れなくなる
