### ISSUE TITLE
ギットハブ講座

### ISSUE THREAD

**Issue by bobtochi** [RyotaTokuda/team-nodaiaken#2]
トクちゃんにギットハブの使い方を教えてもらう。

**Comment by RyotaTokuda** [comment]
@bobtochi 
読んでください

**Comment by RyotaTokuda** [comment]
## 難しいかもしれませんが定期的にわかりやすいサイトのリンクを貼ります

[https://seleck.cc/647](url)

**Comment by bobtochi** [comment]
padのパスワード教えてくれー

**Comment by RyotaTokuda** [comment]
@bobtochi 
了解しまいした
