### ISSUE TITLE
3/1更新　会計タスク一覧

### ISSUE THREAD

**Issue by Designblitz** [RyotaTokuda/team-nodaiaken#20]
### 小田のタスク

- [x] 会員からAA研への入金が確認できるテンプレの作成

- [x] テンプレをテンプレ用のシートに変換する

**Comment by Designblitz** [comment]
### @RyotaTokuda のタスク

> ２月会計

- [x] ２月会計を締めることをAA研メンバーへの告知

- [x] ２月会計の決算

- [x] ２月会計の掲示

1. ワンドラにアップした事の告知

1. 会室のホワイトボードに印刷して掲示

- [x] ２月会計徴収

> 追いコン

- [x] 一次会エクセルシート作成

- [x] 一次会エクセルシートを金子さんに見せ各品目が何年生徴収か確認
##### 一次会に関しては金子さんに従ってください

- [x] 二次会三次会エクセルシート作成

##### 他団体はすでに徴収済みです

- [x] 二次会三次会エクセルシートを水流さんに見せて指示を仰ぐ

##### 恐らくミルさんは酔っ払って記憶がなかったり頼れなかったり色々するのでこちらが気を回すと👍

**Comment by RyotaTokuda** [comment]
@Designblitz 
完璧だわ笑
GitHubいいでしょ〜

**Comment by Designblitz** [comment]
各目標に対する問題や遂行過程はなるべく細かく報告しましょう
問題発覚、システム向上につながります

**Comment by RyotaTokuda** [comment]
> 各目標に対する問題や遂行過程はなるべく細かく報告しましょう
> 問題発覚、システム向上につながります

了解しました
みんなにもいうべきだわ笑

**Comment by Designblitz** [comment]
そう言ってもらえると嬉しいよ

**Comment by Designblitz** [comment]
> > 各目標に対する問題や遂行過程はなるべく細かく報告しましょう
> > 問題発覚、システム向上につながります
> 
> 了解しました
> みんなにもいうべきだわ笑

そう言ってもらえると嬉しいよ

**Comment by RyotaTokuda** [comment]
> ２月会計の決算
2月のシート確認して欲しい
もし、誰も出なかったらこれで決定だから

**Comment by Designblitz** [comment]
会計バックの決算はまだやってないよね？

- [ ] 会計バック金額確認

**Comment by RyotaTokuda** [comment]
## こっちに書くべきだった

かおなとのやりとり
会計バックは得田が持つ

- ミルさんとのやりとり

- 金子さん、くりさん、かおなの2次、３次会の代金

３次会の得田とかおなの買い出し
１次会の代金をみんなから徴収

- 岩手バス代のキャンセル料金どうするか問題

大学側が負担してくれるかもしれない

乗車券がスマホ上で発行されたものは100円だけで済むのが行き帰り合わせて4件

乗車券が紙で発行されたものは簡易書留で郵送するため＆キャンセル料金は不明　2件

上記2件にゆきやは含まれていない

**Comment by Designblitz** [comment]
いいね👍

**Comment by Designblitz** [comment]
岩手キャンセル代終わったはずサヤさんの確認もらって終わり

**Comment by Designblitz** [comment]
@RyotaTokuda 追加タスク

- [ ] ワンドラアップグレードパワポ 作成
@Designblitz 追加タスク

- [ ] 会計マニュアル作成
#### 1年間をかけて作成を考えている

**Comment by Designblitz** [comment]
追加タスク

- [ ] 会計備品購入

1. チャック袋

1. 封筒

@RyotaTokuda 追加タスク

- [x] 追いコン会計締め切りアナウンス（金子さんに確認を含む）

**Comment by RyotaTokuda** [comment]
これcloseで
