### ISSUE TITLE
新学期始まってからやらなくてはいけない事、やりたい事

### ISSUE THREAD

**Issue by Designblitz** [RyotaTokuda/team-nodaiaken#27]
@RyotaTokuda 
- [x] 金子さんの追いコンだい請求
- [x] ユキヤ12月2月春代徴収

**Comment by RyotaTokuda** [comment]
ゆきやの追いコン代は得田が引継ぎましたー！

**Comment by Designblitz** [comment]
大学伸びたのに何もやってなかったね、金子さんと幸也どうするか話したっけ？

**Comment by RyotaTokuda** [comment]
幸也には連絡ずみです
現在、入金待ちです

**Comment by Designblitz** [comment]
ユキヤの入金は全額確認できた？

**Comment by RyotaTokuda** [comment]
確認済

**Comment by Designblitz** [comment]
じゃあこのissue閉じてもいいかな？
一応アンケ

- [x] 小田

- [x] 得田

- [x] サヤさん

**Comment by Designblitz** [comment]
試しでやってみたけどやりすぎ？

**Comment by RyotaTokuda** [comment]
閉じても戻せるから閉じて良いぽかったら閉じても良いかも
