### ISSUE TITLE
4月会計

### ISSUE THREAD

**Issue by Designblitz** [RyotaTokuda/team-nodaiaken#29]

**Comment by RyotaTokuda** [comment]
- そうたろうさんの入金確認

340786

- 残高

428659

- [x] みんなにアナウンスする



- [x] 閉める（30日のmtg後）

- [x] リスト作成後みんなにアナウンス（目標一週間以内）

4月の会計を会室に貼ることを学校が始まってからやる事のイシューに書く
ーーーーーーーーーーーーーーーーーーーーーーーーーーー
2020/05/07に記帳しに行き、リストを作成する

**Comment by Designblitz** [comment]
どうなりました？

**Comment by RyotaTokuda** [comment]
リスト作成完了、確認ののちみんなにアナウンスします

**Comment by Designblitz** [comment]
ここも閉めていいかな？

**Comment by Designblitz** [comment]
4月会計締める
- [x] 小田

- [x] サヤさん

- [x] 得田

**Comment by RyotaTokuda** [comment]
ではcloseで
