### ISSUE TITLE
収穫祭全体説明会

### ISSUE THREAD

**Issue by RyotaTokuda** [RyotaTokuda/team-nodaiaken#3]
# 下記のプリントに関わる方は必ず目を通しておいてください（あくまでまとめです。）
　
　

## 期限のある書類
- 自転車駐輪調査について
　　自転車を何台止めますか？
　　締め切り　10月15日（火）12:50
　　　　

- 収穫祭で車の乗り入れをしますか？
　　10月14日〜10月24日の平日、業務期間中のみ

- パーカー
　締め切り10月11日（金）12時50分

- 宅配物の事前登録
　　平日　8:30〜17:30、宅配物が届く前日まで

- 運営補助員　注意事項
　　シフトの変更の締め切り　10月25日（金）17:00まで

- 塗料、接着剤等の成分等確認結果
　期限　10月18日（金）　
　提出先　収穫祭環境対策委員会

## 確認が必要な書類
- 収穫祭閉会式当日の流れ
　　1団体つき2名参加

- 学生駐輪について
プリントを確認してください

- 収穫祭非常時対応説明開催について
　収穫祭参加団体対象
　　日時　10月24日（木）12:20〜12:55
　　集合　12:15
　　場所　百周年記念講堂
　　内容　プリントを確認してください

- 収穫祭閉会式当日の流れ
　日時　11月6日（水）
　場所　百周年記念講堂
　17:00　百周年記念講堂開場
　1団体つき2名参加必須
　入場時に団体ごとに出席をとります

- ゴミ出し
10月31日〜11月5日［本祭前日〜片付けの日］
詳細はプリントを見てください

**Comment by bobtochi** [comment]
> # 下記のプリントに関わる方は必ず目を通しておいてください（あくまでまとめです。）
> 　
> 　
> 
> ## 期限のある書類
> * 自転車駐輪調査について
>   　　自転車を何台止めますか？
>   　　締め切り　10月15日（火）12:50
> * 収穫祭で車の乗り入れをしますか？
>   　　10月14日〜10月24日の平日、業務期間中のみ
> * パーカー
>   　締め切り10月11日（金）12時50分
> * 宅配物の事前登録
>   　　平日　8:30〜17:30、宅配物が届く前日まで
> * 運営補助員　注意事項
>   　　シフトの変更の締め切り　10月25日（金）17:00まで
> * 塗料、接着剤等の成分等確認結果
>   　期限　10月18日（金）　
>   　提出先　収穫祭環境対策委員会
> 
> ## 確認が必要な書類
> * 収穫祭閉会式当日の流れ
>   　　1団体つき2名参加
> * 学生駐輪について
>   プリントを確認してください
> * 収穫祭非常時対応説明開催について
>   　収穫祭参加団体対象
>   　　日時　10月24日（木）12:20〜12:55
>   　　集合　12:15
>   　　場所　百周年記念講堂
>   　　内容　プリントを確認してください
> * 収穫祭閉会式当日の流れ
>   　日時　11月6日（水）
>   　場所　百周年記念講堂
>   　17:00　百周年記念講堂開場
>   　1団体つき2名参加必須
>   　入場時に団体ごとに出席をとります
> * ゴミ出し
>   10月31日〜11月5日［本祭前日〜片付けの日］
>   詳
