### ISSUE TITLE
追いコン_会計（得田担当）

### ISSUE THREAD

**Issue by RyotaTokuda** [RyotaTokuda/team-nodaiaken#9]
- １次会の会場費

- [x] 3月1日のかおなとのやりとりをGitHubにあげる

**Comment by Designblitz** [comment]
うわあ

**Comment by RyotaTokuda** [comment]
# かおなとのやりとり

- 会計バックは得田が持つ

- ミルさんとのやりとり
金子さん、くりさん、かおなの2次、３次会の代金
３次会の得田とかおなの買い出し
１次会の代金をみんなから徴収

- 岩手バス代のキャンセル料金どうするか問題
大学側が負担してくれるかもしれない

乗車券がスマホ上で発行されたものは100円だけで済むのが行き帰り合わせて4件

乗車券が紙で発行されたものは簡易書留で郵送するため＆キャンセル料金は不明　2件

上記2件にゆきやは含まれていない

**Comment by RyotaTokuda** [comment]
#12

**Comment by RyotaTokuda** [comment]
- [x] くりさんに慰労会の交通費が返金されているか確認する

**Comment by RyotaTokuda** [comment]
@Designblitz 
こんな感じ？
- [x] 金子さんと栗田さんの合計金額4000円をみるさん指定口座に振り込む

- [x] 栗田さんからは2000円未徴収だが、慰労会の交通費をまだ支払っていないので178円をお返しする

- [x] １次会の会場費をようが建て替えてくれているので返金する

- [x] 金子さんの花代を返金する

- [x] 金子さんに１次会の割り方を確認する

- [x] 学年ごとに別々の会計になるので、それぞれ徴収する

- [x] かおなはみるさんから422円返金してもらう

**Comment by RyotaTokuda** [comment]
@Designblitz 
ミルさんから422円返金されてたわ
今日記帳して確認した

**Comment by RyotaTokuda** [comment]
@RyotaTokuda 
金子さんに徴収する
花代返金と徴収代をみて確定させる

**Comment by Designblitz** [comment]
これどうなってる？

**Comment by RyotaTokuda** [comment]
- 金子さんからの徴収

４年生の追いコン代金ー追い込んでの花代である
5256円-4350円＝906円

徴収申請済み
